services:
  php-fpm-8.4:
    build:
      context: ./8.4
      dockerfile: Dockerfile
    image: openpanel/php:8.4-fpm
    container_name: php-fpm-8.4
    restart: unless-stopped
    volumes:
      - html_data:/var/www/html/
      - ./sockets/php:/var/run/php
      - ./php.ini/8.4.ini:/usr/local/etc/php/php.ini
      - /etc/openpanel/wordpress/wp-cli.phar:/usr/local/bin/wp:ro
      - /etc/openpanel/php/composer/v2_composer.phar:/usr/local/bin/composer:ro
      - /etc/openpanel/php/ioncube/ioncube_loader_lin_8.4.so:/usr/local/lib/php/extensions/ioncube_loader.so:ro
      - /etc/openpanel/php/ioncube_extension.ini:/usr/local/etc/php/conf.d/docker-php-ext-ioncube.ini:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy:
      resources:
        limits:
          cpus: "${PHP_FPM_8_4_CPU:-0.125}"
          memory: "${PHP_FPM_8_4_RAM:-0.25G}"
          pids: 100
    networks:
      - www
      - db
